trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'deploy/main.bicep'

variables:
  - name: environmentType
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
      value: develop
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      value: prod
  - group: rm-tob-variables-group-dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PowerShell@2
    displayName: 'Run Bicep Linter'
    inputs:
      targetType: 'inline'
      script: |
        az bicep build --file deploy/main.bicep

  - task: AzureCLI@2
    name: RunPreflightValidation
    displayName: 'Run preflight validation'
    inputs:
      azureSubscription: '$(ARMServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group validate --debug \
          --resource-group '$(ResourceGroupName)' \
          --template-file deploy/main.bicep \
          --parameters environmentName=${{ variables.environmentType }} \
                        applicationName='identity-web'

  - task: AzureCLI@2
    name: DeployInfrastructure
    displayName: 'Deploy infrastructure to Azure'
    inputs:
      azureSubscription: '$(ARMServiceConnection)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az deployment group create \
          --resource-group '$(ResourceGroupName)' \
          --template-file deploy/main.bicep \
          --parameters environmentName=${{ variables.environmentType }} \
                        applicationName='identity-web'
